import { NavLink } from '@/components/NavLink'
import './globals.css'
import { Quicksand } from 'next/font/google'
import { SideNav } from '@/components/SideNav'

const quicksand = Quicksand({ subsets: ['latin']},)

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} flex flex-row`}>
        <div className="flex-1">
          <SideNav />
        </div>
        <div className='w-[84vw] flex flex-col m-0'>
          {children}
        </div>
      </body>
    </html>
  )
}
