import { NavLink } from '@/components/NavLink'
import './globals.css'
import { Quicksand } from 'next/font/google'
import { SideNav } from '@/components/SideNav'
import { TodosProvider } from '@/components/TodosContext'

const quicksand = Quicksand({ subsets: ['latin']},)

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} flex flex-row h-screen overflow-hidden`}>
        <div className="w-[16vw] shrink-0 h-screen sticky top-0">
          <SideNav />
        </div>
        <div className='w-[84vw] h-screen overflow-y-auto flex flex-col m-0 bg-zinc-900'>
          <TodosProvider>{children}</TodosProvider>
        </div>
      </body>
    </html>
  )
}
